# This file contains the config for actionlint.
# See https://github.com/rhysd/actionlint/blob/main/docs/config.md
#
# Primarily, we use this config to define some large runners that are not registered in actionlint
self-hosted-runner:
  labels:
    - ubuntu-latest-xl
    - macos-15-large
    - macos-15-xlarge
    - macos-12
    - ubuntu-24.04-v4
    - ubuntu-24.04-v64

paths:
  '**/*':
    ignore:
      # This is meant to be a temporary workaround for a bug in actionlint. Upstream:
      #    - issue: https://github.com/rhysd/actionlint/issues/511
      #    - PR: https://github.com/rhysd/actionlint/pull/513
      - '"env" is not allowed in "runs" section because .* is a Composite action.*'
