name: Set up mirror certificates
description: Set up mirror certificates

inputs:
  OP_SERVICE_ACCOUNT_TOKEN:
    description: 1Password service account token
    required: true
  NEEDS_SSL_CERTIFICATES:
    description: Whether the action needs to set up SSL certificates
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Install 1Password CLI
      uses: 1password/install-cli-action@9a0c9dd934086b7ab1d90115d455bda1c53c2bdb
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ inputs.OP_SERVICE_ACCOUNT_TOKEN }}

    - name: Update SSL Certificates from 1Password
      if: ${{ inputs.NEEDS_SSL_CERTIFICATES == 'true' }}
      run: |
        op document get --output expensify.ca.crt expensify.ca.crt && sudo cp expensify.ca.crt /usr/local/share/ca-certificates/expensify.ca.crt
        sudo update-ca-certificates
      shell: bash
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ inputs.OP_SERVICE_ACCOUNT_TOKEN }}

