# This action configures Git for OSBotify.
#
# By default, the token it provides is a Github App for Github Authentication.
# GitHub Apps have higher rate limits.
#
# If you only need a local git setup, you can skip that step with SETUP_AS_APP: false

name: Setup Git for OSBotify
description: Setup Git for OSBotify

inputs:
  OP_VAULT:
    description: 1Password vault where OSBotify GPG key can be found
    required: true
  OP_SERVICE_ACCOUNT_TOKEN:
    description: 1Password service account token
    required: true
  OS_BOTIFY_APP_ID:
    description: Application ID for OS Botify
    required: false
  OS_BOTIFY_PRIVATE_KEY:
    description: Private key for OSBotify app
    required: false
  SETUP_AS_APP:
    description: Should we get an app token for OSBotify?
    required: false
    default: 'true'

outputs:
  # Do not try to use this for committing code. Use `secrets.OS_BOTIFY_COMMIT_TOKEN` instead
  OS_BOTIFY_API_TOKEN:
    description: Token to use for GitHub API interactions.
    value: ${{ steps.generateToken.outputs.token }}

runs:
  using: composite
  steps:
    - name: Install 1Password CLI
      uses: 1password/install-cli-action@v1

    - name: Download OSBotify GPG key
      run: op read "op://${{ inputs.OP_VAULT }}/OSBotify-private-key.asc/OSBotify-private-key.asc" --force --out-file ./OSBotify-private-key.asc
      shell: bash
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ inputs.OP_SERVICE_ACCOUNT_TOKEN }}

    - name: Import OSBotify GPG Key
      shell: bash
      run: gpg --import OSBotify-private-key.asc

    - name: Set up git for OSBotify
      shell: bash
      run: |
        git config user.signingkey AEE1036472A782AB
        git config commit.gpgsign true
        git config user.name OSBotify
        git config user.email infra+osbotify@expensify.com

    - name: Sync clock
      shell: bash
      run: sudo sntp -sS time.windows.com
      if: runner.os == 'macOS'

    - name: Generate a token
      id: generateToken
      if: inputs.SETUP_AS_APP == 'true'
      uses: actions/create-github-app-token@9d97a4282b2c51a2f4f0465b9326399f53c890d4
      with:
        app-id: ${{ inputs.OS_BOTIFY_APP_ID }}
        private-key: ${{ inputs.OS_BOTIFY_PRIVATE_KEY }}
