name: Checkout target repo and GitHub Actions repo
description: Checkout target repo and GitHub Actions repo

outputs:
  NAME:
    description: The target repo where this workflow is running (repo name w/o org prefix)
    value: ${{ steps.repo.outputs.NAME }}

runs:
  using: composite
  steps:
    - name: Get target repo name
      id: repo
      run: echo "NAME=$(basename ${{ github.repository }})" >> "$GITHUB_OUTPUT"
      shell: bash

    # v7.0.0
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        path: ${{ steps.repo.outputs.NAME }}

    - name: Checkout Expensify/GitHub-Actions
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        repository: Expensify/GitHub-Actions
        path: GitHub-Actions
