name: Publish package to npmjs

on:
  workflow_call:
    inputs:
      repository:
        description: 'Repository name with owner. For example: "Expensify/eslint-config-expensify"'
        default: ${{ github.repository }}
        required: true
        type: string
      should_run_build:
        description: 'True if we should run npm run build for the package'
        default: false
        required: false
        type: boolean

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a GitHub App token
        id: generateAppToken
        uses: actions/create-github-app-token@9d97a4282b2c51a2f4f0465b9326399f53c890d4
        with:
          app-id: ${{ secrets.OS_BOTIFY_APP_ID }}
          private-key: ${{ secrets.OS_BOTIFY_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          token: ${{ steps.generateAppToken.outputs.token }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install npm packages
        run: npm ci

      # Don't commit the version bump, we will commit later
      - name: Update npm version
        run: npm version patch --git-tag-version false

      - name: Set new version in GitHub ENV
        run: echo "NEW_VERSION=$(jq '.version' package.json)" >> $GITHUB_ENV

      # Copied and edited from: https://github.com/joshjohanning-org/commit-sign-app/blob/main/.github/workflows/commit-sign.yml
      - name: Created signed commit
        run: |
          #!/bin/bash
          set -euxo pipefail

          # Variables
          repository="${{ inputs.repository }}" 
          token="${{ steps.generateAppToken.outputs.token }}"
          version="${{ env.NEW_VERSION }}"
          file1_path="package.json"
          file2_path="package-lock.json"

          # Get the contents of the files; jq -Rs escapes new lines and quotes
          file1_content=$(jq -Rs '.' $file1_path)
          file2_content=$(jq -Rs '.' $file2_path)

          # Get the latest commit
          latest_commit=$(curl -s -H "Authorization: token $token" \
            https://api.github.com/repos/$repository/git/refs/heads/main \
            | jq -r '.object.sha')

          # Get the tree of the latest commit
          base_tree=$(curl -s -H "Authorization: token $token" \
            https://api.github.com/repos/$repository/git/commits/$latest_commit \
            | jq -r '.tree.sha')

          # Create a file of our JSON to send as we can't send it as a string as it's too big
          echo '{
            "base_tree": "'"$base_tree"'",
            "tree": [
              {
                "path": "'"$file1_path"'",
                "mode": "100644",
                "type": "blob",
                "content": '"$file1_content"'
              },
              {
                "path": "'"$file2_path"'",
                "mode": "100644",
                "type": "blob",
                "content": '"$file2_content"'
              }
            ]
          }' > tree_request.json

          # Create a new tree with the new files
          tree=$(curl -s -H "Authorization: token $token" -X POST -d @tree_request.json https://api.github.com/repos/$repository/git/trees)

          # Get the SHA of the new tree
          new_tree_sha=$(echo $tree | jq -r '.sha')

          # Create a new commit pointing to the new tree
          commit=$(curl -sf -H "Authorization: token $token" -X POST \
            -d '{
              "message": "Update version to: '"$version"'",
              "tree": "'"$new_tree_sha"'",
              "parents": ["'"$latest_commit"'"]
            }' https://api.github.com/repos/$repository/git/commits)

          # Get the SHA of the new commit
          new_commit_sha=$(echo $commit | jq -r '.sha')

          # Update the reference of the branch to point to the new commit
          curl -s -H "Authorization: token $token" -X PATCH \
            -d '{
              "sha": "'"$new_commit_sha"'"
            }' https://api.github.com/repos/$repository/git/refs/heads/main
          
          # Set up git user info so we can push a tag
          # os-botify[bot] GitHub App ID can be found here: https://api.github.com/users/os-botify[bot]
          git config --global user.name "os-botify[bot]"
          git config --global user.email "140437396+os-botify[bot]@users.noreply.github.com"
          
          # Fetch the commit that was made via the API
          git fetch origin main   

          # Tag new_commit_sha with our new version
          git tag -a $version $new_commit_sha -m "$version"
          
          # Push the new tag
          git push origin tag $version

      - name: Optionally run `npm run build`
        if: ${{ inputs.should_run_build }}
        run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set name version in GitHub ENV
        run: echo "NAME=$(jq '.name' package.json)" >> $GITHUB_ENV

      - name: Get Pull Request Number
        uses: actions/github-script@v7
        id: pull_request_number
        with:
          script: |
            if (context.issue.number) {
              // Return issue number if present
              return context.issue.number;
            } else {
              // Otherwise return issue number from commit
              return (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0].number;
            }
          result-encoding: string

      - name: Comment on PR
        run: |
          gh pr comment ${{steps.pull_request_number.outputs.result}} --repo ${{ inputs.repository }} --body ":rocket: Published to [npm](https://www.npmjs.com/) in ["${{ env.NEW_VERSION }}"](https://www.npmjs.com/package/"${{ env.NAME }}"/v/"${{ env.NEW_VERSION }}") :tada:"
        env:
          GITHUB_TOKEN: ${{ steps.generateAppToken.outputs.token }}
