name: Publish package to npmjs

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
        description: 'Repository name with owner. For example: "Expensify/eslint-config-expensify"'
      pull_request_number:
        required: true
        type: number
        description: 'Pull request number that was merged to trigger this workflow'

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a GitHub App token
        id: generateAppToken
        uses: actions/create-github-app-token@9d97a4282b2c51a2f4f0465b9326399f53c890d4
        with:
          app-id: ${{ secrets.OS_BOTIFY_APP_ID }}
          private-key: ${{ secrets.OS_BOTIFY_PRIVATE_KEY }}

      # Set up GPG signing by following this: https://stackoverflow.com/a/74071223
      # os-botify GitHub App ID can be found here: https://api.github.com/users/os-botify[bot]
      - name: Set up git user
        run: |
          git config --global user.name "os-botify[bot]"
          git config --global user.email "140437396+os-botify[bot]@users.noreply.github.com"

      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          token: ${{ steps.generateAppToken.outputs.token }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Update npm version
        run: npm version patch

      - name: Set new version in GitHub ENV
        run: echo "NEW_VERSION=$(jq '.version' package.json)" >> $GITHUB_ENV

      - name: Push branch and publish tags
        run: git push main && git push --tags

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Comment on PR
        run: |
          gh pr comment ${{ inputs.pull_request_number }} --repo ${{ inputs.repository }} --body ":rocket: Published in ${{ env.NEW_VERSION }}"
        env:
          GITHUB_TOKEN: ${{ steps.generateAppToken.outputs.token }}
