name: Lint shell code

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize]
    paths: ['**.sh']

jobs:
  lint:
    if: ${{ github.actor != 'OSBotify' || github.event_name == 'workflow_call' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # v4
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Lint shell scripts with ShellCheck
        run: npm run shellCheck
