name: Test

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**/*.[tj]s'
      - '**/*.?[tj]s'
      - 'tsconfig.json'
      - 'package.json'
      - 'package-lock.json'
      - '.nvmrc'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: Checkout
        uses: useblacksmith/checkout@1c9394c220d293645707b625ba9d79685f093a8f # v1

      # v6.1.0
      - name: Setup Node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install npm packages
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Tell people how to run the failing check
        if: failure()
        run: echo "::error::The test check failed! To run it locally, run \`npm ci && npm test\` from the GitHub-Actions repo root."
