# Note: This workflow is configured to run on all pull requests throughout the Expensify org, not just this repo.
# That has a few consequences:
#    - We need to checkout the repo it's running on, and not just the GitHub-Actions repo
#    - branch and path matching does not work in the workflow layer. From the docs: https://docs.github.com/en/enterprise-cloud@latest/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/available-rules-for-rulesets#supported-event-triggers
#        > Any filters you specify for the supported events are ignored - for example, branches, branches-ignore, paths, types and so on. The workflow is only triggered, and is always triggered, by the default activity types of the supported events
name: Validate Github Actions and Workflows

on: pull_request

jobs:
  validateSchemas:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.actor, '[bot]') && github.actor != 'MelvinBot' && github.actor != 'botify' && github.actor != 'OSBotify' }}
    steps:
      - name: Checkout repos
        id: repo
        uses: Expensify/GitHub-Actions/checkoutRepoAndGitHubActions@main

      # v4.3.0
      - name: Setup Node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e

      # Install node to get the ajv-cli
      - name: Install node modules
        run: npm i -g ajv-cli@5.0.0

      - name: Validate action and workflow schemas
        run: GitHub-Actions/scripts/validateWorkflowSchemas.sh
        env:
          REPO_ROOT: ${{ steps.repo.outputs.NAME }}

      - name: Tell people how to run the failing check
        if: failure()
        run: echo "::error::The validateWorkflowSchemas check failed! To run it locally, go to the root of ${{ steps.repo.outputs.NAME }} and run <path_to_github_actions_repo>/scripts/validateWorkflowSchemas.sh"

  actionlint:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.actor, '[bot]') && github.actor != 'MelvinBot' && github.actor != 'botify' && github.actor != 'OSBotify' }}
    steps:
      - name: Checkout repos
        id: repo
        uses: Expensify/GitHub-Actions/checkoutRepoAndGitHubActions@main

      - name: Lint workflows with actionlint
        run: GitHub-Actions/scripts/actionlint.sh
        env:
          REPO_ROOT: ${{ steps.repo.outputs.NAME }}

      - name: Tell people how to run the failing check
        if: failure()
        run: echo "::error::The actionlint check failed! To run it locally, go to the root of ${{ steps.repo.outputs.NAME }} and run <path_to_github_actions_repo>/scripts/actionlint.sh"

  validateImmutableActionRefs:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.actor, '[bot]') && github.actor != 'MelvinBot' && github.actor != 'botify' && github.actor != 'OSBotify' }}
    steps:
      - name: Checkout repos
        id: repo
        uses: Expensify/GitHub-Actions/checkoutRepoAndGitHubActions@main

      - name: Validate actions refs are immutable
        run: GitHub-Actions/scripts/validateImmutableActionRefs.sh
        env:
          REPO_ROOT: ${{ steps.repo.outputs.NAME }}

      - name: Tell people how to run the failing check
        if: failure()
        run: echo "::error::The validateImmutableActionRefs check failed! To run it locally, go to the root of ${{ steps.repo.outputs.NAME }} and run <path_to_github_actions_repo>/scripts/validateImmutableActionRefs.sh"
