name: Validate Github Actions and Workflows

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [staging, production]
    paths: ['.github/**']

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # v4
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: actions/setup-node@v4

      - name: Install node modules
        run: npm ci

      - name: Validate actions and workflows
        run: .github/scripts/validateActionsAndWorkflows.sh
