name: Validate Github Actions and Workflows

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [staging, production]
    paths: ['.github/**']

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      # v4.2.2
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      # v4.3.0
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e

      - name: Install node modules
        run: npm ci

      - name: Validate actions and workflows
        run: .github/scripts/validateActionsAndWorkflows.sh
